export const api_endpoint = 'https://api-ap-south-1.hygraph.com/v2/clcvxei2o19ix01t57r8egwgt/master';
export const CMStitle = 'CommCMS';
export const CMSdescription = 'Generated by create next app';
export const CMSurl = '#';
export const BGCMS = 'https://mir-s3-cdn-cf.behance.net/project_modules/fs/712cd661356955.5a6b8679a39e7.gif';
export const LOGOCMS = 'https://qph.cf2.quoracdn.net/main-qimg-83cd560099d576d21de9cf666e7cad1e';
